#!/usr/bin/env python3
"""Render DESIGN_SYSTEM.md from brxprod/get-context + extract.php output.

Usage: render.py CONTEXT_JSON DATA_JSON OUTPUT_MD

Only the region between the design-system fences is (re)written; anything the
user adds outside the fences survives regeneration.
"""
import json
import os
import re
import sys
from collections import OrderedDict

START = "<!-- design-system:start — generated by /design-system; edits inside this fence are overwritten -->"
END = "<!-- design-system:end -->"

SIZES = ["3xs", "2xs", "xs", "s", "m", "l", "xl", "2xl", "3xl", "4xl", "5xl", "6xl"]
SIZE_RE = "|".join(sorted(SIZES, key=len, reverse=True))
RAMP_RE = re.compile(r"^(?P<stem>.+)-(?P<kind>[ldt])-(?P<n>\d+)(?P<suffix>-text)?$")

# Concept -> candidate stems (prefix is added at match time).
# {size} = t-shirt scale, {n} = number, {word} = named member.
# Wireframes names are verified; Core Framework candidates are best guesses
# until a Core Framework site has been run through this (see SKILL.md).
ROLES = [
    ("Spacing scale", ["space-{size}"]),
    ("Font-size scale", ["text-{size}"]),
    ("Radius scale", ["radius-{size}"]),
    ("Shadow scale", ["shadow-{size}"]),
    ("Section padding (block)", ["section-space-vertical", "section-padding-block", "section-space-y", "section-space"]),
    ("Section padding (inline)", ["section-space-horizontal", "section-padding-inline", "section-space-x", "gutter"]),
    ("Content gap", ["content-gap"]),
    ("Container gap", ["container-gap"]),
    ("Grid gap", ["grid-gap"]),
    ("Container width", ["container-width", "container-max-width", "max-width"]),
    ("Fixed widths", ["width-{n}"]),
    ("Text measure", ["text-width-{size}"]),
    ("Heading measure", ["title-width-{size}"]),
    ("Body line height", ["line-height-body", "body-line-height"]),
    ("Heading line height", ["line-height-heading", "heading-line-height"]),
    ("Transitions", ["transition-{size}"]),
    ("Aspect ratios", ["ratio-{word}", "aspect-{word}"]),
    ("Grid templates", ["grid-{n}"]),
    ("Neutral greys", ["color-neutral-{n}", "neutral-{n}", "base-{n}"]),
    ("Overlay colour", ["color-overlay", "overlay"]),
]


def load(path):
    try:
        with open(path) as fh:
            doc = json.load(fh)
    except (OSError, ValueError):
        return None
    if isinstance(doc, dict) and doc.get("ok") is False:
        return None
    return doc.get("data", doc) if isinstance(doc, dict) else doc


def fail(msg):
    sys.stderr.write("render.py: %s\n" % msg)
    sys.exit(1)


def cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


def compact(value, limit=80):
    value = re.sub(r"\s+", " ", value or "").strip()
    return value if len(value) <= limit else value[: limit - 1] + "…"


def size_key(member):
    if member in SIZES:
        return (0, SIZES.index(member), member)
    if member.isdigit():
        return (1, int(member), member)
    return (2, 0, member)


class Tokens:
    def __init__(self, variables):
        self.values = OrderedDict((v["name"], v.get("value", "")) for v in variables)
        self.category = {v["name"]: v.get("category") or "Uncategorised" for v in variables}

    def target(self, name):
        m = re.fullmatch(r"var\(\s*--([\w-]+)\s*(?:,.*)?\)", (self.values.get(name) or "").strip())
        return m.group(1) if m and m.group(1) in self.values else None

    def resolve(self, name, depth=0):
        nxt = self.target(name)
        if nxt and depth < 8:
            return self.resolve(nxt, depth + 1)
        return self.values.get(name, "")

    def display(self, name):
        """Readable value: fluid clamps as `min → max`, aliases named."""
        resolved = self.resolve(name)
        m = re.fullmatch(r"clamp\(\s*([^,]+?)\s*,.*,\s*([^,()]+?)\s*\)", re.sub(r"\s+", " ", resolved.strip()))
        shown = "%s → %s (fluid)" % (m.group(1), m.group(2)) if m else compact(resolved)
        direct = self.target(name)
        if direct and "-fluid-" not in direct:
            return "`--%s` = %s" % (direct, shown)
        return shown


def is_hidden(name):
    # *-fluid-* are scale primitives reached through their non-fluid alias.
    return "-fluid-" in name or name.endswith("-fluid")


def detect_framework(ctx, names):
    fw = (ctx or {}).get("framework") or {}
    if fw.get("detected"):
        return fw["detected"], fw.get("variablePrefix") or "", "brxprod/get-context"
    if sum(n.startswith("brxw-") for n in names) >= 10:
        return "bricks-wireframes", "brxw-", "inferred from variable names"
    if {"space-m", "text-m"} & set(names):
        return "core-framework", "", "inferred from variable names"
    return "unknown", "", "inferred from variable names"


def layer_of(name, prefix, category):
    if name.startswith("brxp-"):
        return "brxp"
    if name.startswith("bricks-") or (category or "").lower() == "not used":
        return "other"
    if prefix:
        return "framework" if name.startswith(prefix) else "other"
    return "framework"


def collapse_ramps(names):
    """Split names into (plain names, ramp summaries) for l/d/t shade ramps."""
    ramps = OrderedDict()
    plain = []
    for n in names:
        m = RAMP_RE.match(n)
        if m:
            key = (m.group("stem"), m.group("suffix") or "")
            entry = ramps.setdefault(key, {"kinds": set(), "nums": set()})
            entry["kinds"].add(m.group("kind"))
            entry["nums"].add(int(m.group("n")))
        else:
            plain.append(n)
    summaries = []
    for (stem, suffix), e in ramps.items():
        nums = sorted(e["nums"])
        span = "%d…%d" % (nums[0], nums[-1]) if len(nums) > 1 else str(nums[0])
        summaries.append("`--%s-{%s}-{%s}%s`" % (stem, ",".join(sorted(e["kinds"])), span, suffix))
    return plain, summaries


def role_matches(tokens, prefix, pattern):
    regex = re.escape(prefix + pattern)
    regex = regex.replace(re.escape("{size}"), "(?P<m>%s)" % SIZE_RE)
    regex = regex.replace(re.escape("{n}"), r"(?P<m>\d+)")
    regex = regex.replace(re.escape("{word}"), r"(?P<m>[a-z][a-z-]*)")
    found = []
    for n in tokens.values:
        if is_hidden(n):
            continue
        m = re.fullmatch(regex, n)
        if m:
            found.append((m.groupdict().get("m"), n))
    return found


def concept_rows(tokens, prefix):
    rows = []
    for label, patterns in ROLES:
        hit = None
        for pattern in patterns:
            found = role_matches(tokens, prefix, pattern)
            if found:
                hit = (pattern, found)
                break
        if not hit:
            rows.append((label, "— not found", ""))
            continue
        pattern, found = hit
        if "{" not in pattern:
            name = found[0][1]
            rows.append((label, "`--%s`" % name, tokens.display(name)))
            continue
        members = sorted((m for m, _ in found), key=size_key)
        token = "`--%s`" % (prefix + pattern.split("{")[0] + "{" + ", ".join(members) + "}")
        sample = next((n for m, n in found if m == "m"), found[0][1])
        rows.append((label, token, "e.g. `--%s` = %s" % (sample, tokens.display(sample))))
    return rows


def scale_order(name):
    """Sort key putting scale members in size order: space-3xs … space-5xl."""
    m = re.fullmatch(r"(.+)-(%s|\d+)" % SIZE_RE, name)
    return (m.group(1),) + size_key(m.group(2)) if m else (name, -1, 0, "")


def variables_section(tokens, names, heading_level="###"):
    out = []
    by_cat = OrderedDict()
    for n in sorted(names, key=scale_order):
        by_cat.setdefault(tokens.category[n], []).append(n)
    for cat in sorted(by_cat):
        plain, ramps = collapse_ramps(by_cat[cat])
        out.append("%s %s (%d)\n" % (heading_level, cat, len(by_cat[cat])))
        if ramps:
            out.append("Shade ramps: " + ", ".join(ramps) + "\n")
        if plain:
            out.append("| Variable | Value |\n|---|---|")
            for n in plain:
                out.append("| `--%s` | %s |" % (n, cell(tokens.display(n))))
            out.append("")
    return out


def render(ctx, data):
    site = data.get("site", {})
    variables = data.get("variables", [])
    tokens = Tokens(variables)
    names = list(tokens.values)
    framework, prefix, source = detect_framework(ctx, names)

    layers = {"framework": [], "brxp": [], "other": []}
    for n in names:
        if not is_hidden(n):
            layers[layer_of(n, prefix, tokens.category[n])].append(n)

    plugins = data.get("plugins", [])
    brxprod = next((p for p in plugins if "productivity" in p["name"].lower()), None)
    ctx = ctx or {}
    code = ctx.get("codeManager") or {}
    sg = ctx.get("styleGuide") or {}

    L = []
    L.append("## Site\n")
    L.append("| | |\n|---|---|")
    L.append("| URL | %s |" % site.get("url", "?"))
    L.append("| Novamira profile | `%s` |" % os.environ.get("NOVAMIRA_SITE", "?"))
    L.append("| WordPress / Bricks | %s / %s |" % (site.get("wordpress"), site.get("bricks")))
    L.append("| BRXProd | %s |" % (brxprod["version"] if brxprod else "not active"))
    L.append("| Framework | **%s** — prefix `%s` (%s) |" % (framework, prefix or "(none)", source))
    L.append("| Code manager | %s%s |" % (
        ", ".join(code.get("detected") or []) or "none detected",
        " — `brxprod/create-snippet` writes drafts" if code.get("canCreateSnippet") else ""))
    L.append("| Style Guide page | %s |" % ("ID %s" % sg.get("pageId") if sg.get("exists") else "none"))
    L.append("| Active plugins | %s |" % cell(", ".join("%s %s" % (p["name"], p["version"]) for p in plugins)))
    L.append("| Generated | %s |" % data.get("generatedAt", "?"))
    L.append("")

    if framework == "core-framework":
        L.append("> **Core Framework support is provisional.** The concept map below uses guessed "
                 "names. Verify against the variable list and update `ROLES` in "
                 "`.claude/skills/design-system/scripts/render.py`.")
        if data.get("coreFrameworkOptions"):
            L.append("> Core Framework options found: " + ", ".join("`%s`" % o for o in data["coreFrameworkOptions"]))
        L.append("")
    if framework == "unknown":
        L.append("> **No supported framework detected.** Only BRXProd (`brxp-*`) tokens and site "
                 "variables are listed; the concept map will be mostly empty.\n")

    L.append("## Concept map — use these names\n")
    L.append("House CSS rules refer to concepts; this table gives this site's actual token. "
             "If a concept says *not found*, there is no token for it — say so and use a literal, "
             "never invent a name.\n")
    L.append("| Concept | Token | Value |\n|---|---|---|")
    for label, token, value in concept_rows(tokens, prefix):
        L.append("| %s | %s | %s |" % (label, token, cell(value)))
    brand = [n for n in ("brxp-primary", "brxp-secondary", "brxp-surface", "brxp-info",
                         "brxp-success", "brxp-warning", "brxp-danger")]
    palette_vars = set()
    for p in data.get("palettes", []):
        for c in p["colors"]:
            m = re.search(r"var\(\s*--([\w-]+)", c.get("raw") or "")
            if m:
                palette_vars.add(m.group(1))
    present = [n for n in brand if n in palette_vars or n in tokens.values]
    if present:
        _, shade_ramps = collapse_ramps(sorted(n for n in palette_vars if n.startswith("brxp-")))
        L.append("| Brand & status colours (BRXProd) | %s | shades: %s; text on a colour: `--brxp-a11y-{colour}[-{l,d}-N]-text` |"
                 % (", ".join("`--%s`" % n for n in present), ", ".join(shade_ramps) or "none"))
    L.append("")

    label = {"bricks-wireframes": "Bricks Wireframes", "core-framework": "Core Framework"}.get(framework, framework)
    L.append("## Framework tokens — %s (%d)\n" % (label, len(layers["framework"])))
    L.append("`*-fluid-*` primitives are omitted: always use the non-fluid name.\n")
    L.extend(variables_section(tokens, layers["framework"]))

    L.append("## BRXProd tokens — `brxp-*`, common to every framework (%d)\n" % len(layers["brxp"]))
    L.extend(variables_section(tokens, layers["brxp"]))

    if layers["other"]:
        L.append("## Other variables (%d)\n" % len(layers["other"]))
        L.append("Framework configuration or third-party values — not for use in component CSS.\n")
        L.extend(variables_section(tokens, layers["other"]))

    L.append("## Colour palettes\n")
    for p in data.get("palettes", []):
        refs = []
        for c in p["colors"]:
            m = re.search(r"var\(\s*--([\w-]+)", c.get("raw") or "")
            refs.append(m.group(1) if m else (c.get("raw") or c.get("hex") or c.get("name")))
        plain, ramps = collapse_ramps(refs)
        if p["name"].lower() == "default":
            L.append("- **%s** (%d) — Bricks' built-in palette; not part of the design system." % (p["name"], len(refs)))
            continue
        L.append("- **%s** (%d): %s" % (p["name"], len(refs), ", ".join(["`--%s`" % r for r in plain] + ramps)))
    L.append("")

    L.append("## Global classes\n")
    plugin_sets = (ctx.get("brxprod") or {}).get("classCategories") or {}
    if plugin_sets:
        installed = ["%s (%s)" % (v.get("label", k), "installed" if v.get("installed") else "**not installed**")
                     for k, v in plugin_sets.items()]
        L.append("BRXProd class sets: " + ", ".join(installed) + ". Plugin classes are locked — never edit their CSS.\n")
    by_cat = OrderedDict()
    style_guide = 0
    for c in data.get("classes", []):
        if re.match(r"sg\d+-", c["name"]):
            style_guide += 1
            continue
        by_cat.setdefault(c.get("category") or "Uncategorised", []).append(c)
    for cat in sorted(by_cat):
        items = by_cat[cat]
        locked = all(c["locked"] for c in items)
        L.append("**%s** (%d%s): %s\n" % (cat, len(items), ", locked" if locked else "",
                                          ", ".join("`%s`" % c["name"] for c in sorted(items, key=lambda c: c["name"]))))
    if style_guide:
        L.append("Style Guide classes: %d `sg{n}-*` classes omitted — the Style Guide generator owns them.\n" % style_guide)

    L.append("## Theme styles\n")
    for t in data.get("themeStyles", []):
        cond = ", ".join(t["conditions"]) or "**no conditions — inactive**"
        L.append("- `%s` — conditions: %s" % (t["label"], cond))
    L.append("")
    return "\n".join(L)


def write(path, body):
    block = START + "\n\n" + body.rstrip() + "\n\n" + END
    if os.path.exists(path):
        with open(path) as fh:
            current = fh.read()
        if START.split(" —")[0] in current and END in current:
            head = current.split(START.split(" —")[0], 1)[0]
            tail = current.split(END, 1)[1]
            out = head + block + tail
        else:
            out = current.rstrip() + "\n\n" + block + "\n"
    else:
        out = (
            "# Design system\n\n"
            "Generated from the connected site by the `/design-system` skill. "
            "Regenerate after the site's variables, classes or palettes change.\n\n"
            + block
            + "\n\n## Project notes\n\n"
            "Hand-written notes go here, outside the generated fence, so they survive regeneration.\n"
        )
    with open(path, "w") as fh:
        fh.write(out)


def main():
    if len(sys.argv) != 4:
        fail("usage: render.py CONTEXT_JSON DATA_JSON OUTPUT_MD")
    ctx = load(sys.argv[1])
    result = load(sys.argv[2])
    if not isinstance(result, dict):
        fail("execute-php returned no data — check `novamira doctor --json`")
    if result.get("success") is False:
        fail("extract.php failed: %s" % result.get("error_message"))
    data = result.get("return_value", result)
    write(sys.argv[3], render(ctx, data))
    framework = detect_framework(ctx, [v["name"] for v in data.get("variables", [])])
    print("Wrote %s — framework %s, %d variables, %d classes" % (
        sys.argv[3], framework[0], len(data.get("variables", [])), len(data.get("classes", []))))


if __name__ == "__main__":
    main()
